# frontend/nginx.conf
server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        
        # O "coração" das Single Page Applications (SPA):
        # Se a rota não for um arquivo físico, joga para o index.html do React
        try_files $uri $uri/ /index.html;
    }
}