services:
  nginx:
    image: nginx:alpine
    container_name: fin_nginx
    restart: unless-stopped
    ports:
      - "80:80" # A ÚNICA porta aberta
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - fin_network

  postgres_db:
    image: postgres:17-alpine
    container_name: fin_postgres
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fin_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend
    container_name: fin_backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DB_HOST=postgres_db # Explícito para o Service Discovery interno
    # REMOVIDO: ports - "8000:8000". Todo tráfego deve passar pelo Nginx.
      - TZ=America/Sao_Paulo
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - fin_network

  # ADICIONADO: O serviço do frontend que o Nginx estava exigindo
  frontend:
    build: 
      context: ./frontend
    container_name: fin_frontend
    restart: unless-stopped
    networks:
      - fin_network

volumes:
  postgres_data:

networks:
  fin_network:
    driver: bridge