worker_processes auto;

# Contexto de eventos (I/O) 
events {
    worker_connections 1024;
    use epoll;
}

# Contexto HTTP (tráfego web)
http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Otimizações de I/O
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;

    # Pra evitar os vacilão de tentar esgotar a quantidade máxima de conexões simultâneas
    client_body_timeout 10s;
    client_header_timeout 10s;
    keepalive_timeout 5s 5s;
    send_timeout 10s;

    # ZONA DAS DIRETIVAS DE SEGURANÇA
    server_tokens off; # Oculta a versão do Nginx (Evita CVE targeted attacks)
    
    # Previne Clickjacking (Não permite que o site rode em iframes)
    add_header X-Frame-Options DENY always;
    
    # Previne ataques de MIME Sniffing
    add_header X-Content-Type-Options nosniff always;
    
    # Restrição de acesso a recursos externos (Evita ataques XSS)
    add_header Content-Security-Policy "default-src 'self'; connect-src 'self' /api-financeira/;" always;
    
    # HSTS (Informa aos navegadores para SÓ usarem HTTPS
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    
    # Rate Limiting Memory Zone
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=5r/s;
    
    # BLOCO SERVER
    # Tŕafego HTTP redirecionado para HTTPS
    server {
        listen 80;
        server_name _;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name localhost; 

        # Path dos certificados
        ssl_certificate /etc/nginx/certs/nginx-selfsigned.crt;
        ssl_certificate_key /etc/nginx/certs/nginx-selfsigned.key;

        # protocolos de criptografia
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;
        ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;

        # ROTA 1: FRONTEND (React)
        location / {
            proxy_pass http://fin_frontend:80;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Cache-Control para arquivos estáticos
            expires 1h;
            add_header Cache-Control "public, no-transform";
        }

        # ROTA 2: BACKEND (FastAPI)
        location /api-financeira/ {
            # Bloqueio de IP agressivo: burst 10 sem delay.
            limit_req zone=api_limit burst=10 nodelay;
            
            proxy_pass http://fin_backend:8000;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}